print("FFFFFFF    U       U      NN      NN")
print("FF         U       U      NNN     NN")
print("FFFFFFF    U       U      NN  N   NN")
print("FF          U     U       NN   N  NN ")
print("FF            UUU         NN     NNN")